### ISSUE TITLE
Версия

### ISSUE THREAD

**Issue by VZhyrytskiy** [kapikapi/shop#1]
Более свежую версию Angular и Angular-CLI не получится поставить?

**Comment by kapikapi** [comment]
У меня старая нода (на проекте такая, поэтому не хочется менять), но действительно можно поправить до 5ой версии, спасибо!

**Comment by VZhyrytskiy** [comment]
ок

**Comment by kapikapi** [comment]
В рамках начиная с Task 3 используется 5ая версия
